In [5]:
text = ['This is a line',
       'This is another line',
       'Completely different line']

<h1>CountVectoriser</h1>

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv = CountVectorizer()

In [8]:
sparse_matrix = cv.fit_transform(text)

In [9]:
#help(CountVectorizer)

In [10]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [11]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [12]:
c = CountVectorizer(stop_words='english')

In [13]:
sparse_matrix = c.fit_transform(text)

In [17]:
sparse_matrix.sum(axis=0)

matrix([[1, 1, 3]], dtype=int64)

In [14]:
sparse_matrix.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [15]:
c.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [18]:
c.get_feature_names_out()

dict_keys(['line', 'completely', 'different'])

<h1>TF-IDF</h1>
**BOW --> TfIDF**

In [19]:
from sklearn.feature_extraction.text import TfidfTransformer

In [23]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [24]:
tfidf = TfidfTransformer()

In [26]:
results = tfidf.fit_transform(sparse_matrix)

In [27]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
tv = TfidfVectorizer()

In [31]:
tv_results = tv.fit_transform(text)

In [32]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])